# Generated by Django 3.0.5 on 2020-04-10 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_a', '0004_auto_20200410_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='user',
            new_name='userb',
        ),
    ]
