# Generated by Django 3.0.5 on 2020-04-10 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_a', '0005_auto_20200410_2048'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budget',
        ),
    ]
