# Generated by Django 3.0.5 on 2020-04-10 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_a', '0006_delete_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='cash',
        ),
    ]
