# Generated by Django 3.0.5 on 2020-04-14 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashCount', '0003_fixbudetmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashmemo',
            name='given',
            field=models.BooleanField(default=False),
        ),
    ]
