# Generated by Django 3.0.5 on 2020-04-17 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashCount', '0004_auto_20200414_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashmemo',
            name='given',
        ),
    ]
